// Display name -> the lowercase FDev symbol Ardent indexes commodities by.
// Generated from EDCD/FDevIDs commodity.csv and rare_commodity.csv; names
// that squash to their own symbol would work without it, but 115 do not
// ("Agri-Medicines" is agriculturalmedicines, "Limpets" is drones).
const SYMBOLS = {
  "advanced catalysers": "advancedcatalysers",
  "advanced medicines": "advancedmedicines",
  "aepyornis egg": "cetiaepyornisegg",
  "aganippe rush": "aganipperush",
  "agri-medicines": "agriculturalmedicines",
  "agronomic treatment": "agronomictreatment",
  "ai relics": "airelics",
  "alacarakmo skin art": "alacarakmoskinart",
  "albino quechua mammoth meat": "albinoquechuamammoth",
  "alexandrite": "alexandrite",
  "algae": "algae",
  "altairian skin": "altairianskin",
  "aluminium": "aluminium",
  "alya body soap": "alyabodilysoap",
  "ancient artefact": "usscargoancientartefact",
  "ancient key": "ancientkey",
  "anduliga fire works": "anduligafireworks",
  "animal meat": "animalmeat",
  "animal monitors": "animalmonitors",
  "anomaly particles": "p_particulatesample",
  "antimatter containment unit": "antimattercontainmentunit",
  "antique jewellery": "antiquejewellery",
  "antiquities": "antiquities",
  "any na coffee": "anynacoffee",
  "apa vietii": "apavietii",
  "aquaponic systems": "aquaponicsystems",
  "arouca conventual sweets": "aroucaconventualsweets",
  "articulation motors": "articulationmotors",
  "assault plans": "assaultplans",
  "atmospheric processors": "atmosphericextractors",
  "auto-fabricators": "autofabricators",
  "az cancri formula 42": "azcancriformula42",
  "azure milk": "bluemilk",
  "baked greebles": "bakedgreebles",
  "baltah'sine vacuum krill": "baltahsinevacuumkrill",
  "banki amphibious leather": "bankiamphibiousleather",
  "basic medicines": "basicmedicines",
  "bast snake gin": "bastsnakegin",
  "bastnasite": "bastnasite",
  "battle weapons": "battleweapons",
  "bauxite": "bauxite",
  "beer": "beer",
  "belalans ray leather": "belalansrayleather",
  "benitoite": "benitoite",
  "bertrandite": "bertrandite",
  "beryllium": "beryllium",
  "bioreducing lichen": "bioreducinglichen",
  "biowaste": "biowaste",
  "bismuth": "bismuth",
  "black box": "usscargoblackbox",
  "bone fragments": "thargoidbonefragments",
  "bootleg liquor": "bootlegliquor",
  "borasetani pathogenetics": "borasetanipathogenetics",
  "bromellite": "bromellite",
  "buckyball beer mats": "buckyballbeermats",
  "building fabricators": "buildingfabricators",
  "burnham bile distillate": "burnhambiledistillate",
  "caustic tissue sample": "thargoidgeneratortissuesample",
  "cd-75 kitten brand coffee": "cd75catcoffee",
  "centauri mega gin": "centaurimegagin",
  "ceramic composites": "ceramiccomposites",
  "ceremonial heike tea": "ceremonialheiketea",
  "ceti rabbits": "cetirabbits",
  "chameleon cloth": "chameleoncloth",
  "chateau de aegaeon": "chateaudeaegaeon",
  "chemical waste": "chemicalwaste",
  "cherbones blood crystals": "cherbonesbloodcrystals",
  "chi eridani marine paste": "chieridanimarinepaste",
  "classified experimental equipment": "classifiedexperimentalequipment",
  "clothing": "clothing",
  "cmm composite": "cmmcomposite",
  "cobalt": "cobalt",
  "coffee": "coffee",
  "coltan": "coltan",
  "combat stabilisers": "combatstabilisers",
  "commercial samples": "comercialsamples",
  "computer components": "computercomponents",
  "conductive fabrics": "conductivefabrics",
  "consumer technology": "consumertechnology",
  "copper": "copper",
  "coquim spongiform victuals": "coquimspongiformvictuals",
  "coral sap": "coralsap",
  "crom silver fesh": "animaleffigies",
  "crop harvesters": "cropharvesters",
  "cryolite": "cryolite",
  "crystalline spheres": "crystallinespheres",
  "curated commodity package": "curatedcommodity",
  "cyst specimen": "thargoidcystspecimen",
  "damaged escape pod": "damagedescapepod",
  "damna carapaces": "damnacarapaces",
  "data core": "datacore",
  "delta phoenicis palms": "deltaphoenicispalms",
  "deuringas truffles": "deuringastruffles",
  "deuterium": "deuterium",
  "diamond": "diamond",
  "diplomatic bag": "diplomaticbag",
  "diso ma corn": "disomacorn",
  "domestic appliances": "domesticappliances",
  "duradrives": "duradrives",
  "earth relics": "earthrelics",
  "eden apples of aerial": "aerialedenapple",
  "eleu thermals": "eleuthermals",
  "emergency power cells": "emergencypowercells",
  "encrypted correspondence": "encryptedcorrespondence",
  "encrypted data storage": "encripteddatastorage",
  "energy grid assembly": "powergridassembly",
  "eranin pearl whisky": "eraninpearlwhisky",
  "eshu umbrellas": "eshuumbrellas",
  "esuseku caviar": "esusekucaviar",
  "ethgreze tea buds": "ethgrezeteabuds",
  "evacuation shelter": "evacuationshelter",
  "exhaust manifold": "exhaustmanifold",
  "experimental chemicals": "usscargoexperimentalchemicals",
  "explosives": "explosives",
  "festive gifts": "personalgifts",
  "fish": "fish",
  "food cartridges": "foodcartridges",
  "fossil remnants": "fossilremnants",
  "fruit and vegetables": "fruitandvegetables",
  "fujin tea": "fujintea",
  "galactic travel guide": "galactictravelguide",
  "gallite": "gallite",
  "gallium": "gallium",
  "geawen dance dust": "geawendancedust",
  "gene bank": "genebank",
  "geological equipment": "geologicalequipment",
  "geological samples": "geologicalsamples",
  "gerasian gueuze beer": "gerasiangueuzebeer",
  "giant irukama snails": "giantirukamasnails",
  "giant verrix": "giantverrix",
  "gilya signature weapons": "gilyasignatureweapons",
  "gold": "gold",
  "goman yaupon coffee": "gomanyauponcoffee",
  "goslarite": "goslarite",
  "grain": "grain",
  "grandidierite": "grandidierite",
  "guardian casket": "ancientcasket",
  "guardian orb": "ancientorb",
  "guardian relic": "ancientrelic",
  "guardian tablet": "ancienttablet",
  "guardian totem": "ancienttotem",
  "guardian urn": "ancienturn",
  "h.e. suits": "hazardousenvironmentsuits",
  "haematite": "haematite",
  "hafnium 178": "hafnium178",
  "haiden black brew": "haidneblackbrew",
  "hardware diagnostic sensor": "diagnosticsensor",
  "harma silver sea rum": "harmasilversearum",
  "havasupai dream catcher": "havasupaidreamcatcher",
  "heatsink interlink": "heatsinkinterlink",
  "helium": "helium",
  "helium-3": "helium3",
  "helvetitj pearls": "helvetitjpearls",
  "hip 10175 bush meat": "hip10175bushmeat",
  "hip 118311 swarm": "hip118311swarm",
  "hip organophosphates": "hiporganophosphates",
  "hip proto-squid": "hip41181squid",
  "hn shock mount": "hnshockmount",
  "holva duelling blades": "holvaduellingblades",
  "honesty pills": "honestypills",
  "hostages": "hostage",
  "hr 7221 wheat": "hr7221wheat",
  "hydrogen fuel": "hydrogenfuel",
  "hydrogen peroxide": "hydrogenperoxide",
  "imperial slaves": "imperialslaves",
  "impure spire mineral": "unknownmineral",
  "indi bourbon": "indibourbon",
  "indite": "indite",
  "indium": "indium",
  "insulating membrane": "insulatingmembrane",
  "ion distributor": "iondistributor",
  "iridium": "iridium",
  "jadeite": "jadeite",
  "jaques quinentian still": "jaquesquinentianstill",
  "jaradharre puzzle box": "jaradharrepuzzlebox",
  "jaroua rice": "jarouarice",
  "jotun mookah": "jotunmookah",
  "kachirigin filter leeches": "kachiriginleaches",
  "kamitra cigars": "kamitracigars",
  "kamorin historic weapons": "kamorinhistoricweapons",
  "karetii couture": "karetiicouture",
  "karsuki locusts": "karsukilocusts",
  "kinago violins": "kinagoinstruments",
  "kongga ale": "konggaale",
  "koro kung pellets": "korrokungpellets",
  "land enrichment systems": "terrainenrichmentsystems",
  "landmines": "landmines",
  "lanthanum": "lanthanum",
  "large survey data cache": "largeexplorationdatacash",
  "lavian brandy": "lavianbrandy",
  "leather": "leather",
  "leathery eggs": "alieneggs",
  "leestian evil juice": "leestianeviljuice",
  "lepidolite": "lepidolite",
  "limpets": "drones",
  "liquid oxygen": "liquidoxygen",
  "liquor": "liquor",
  "lithium": "lithium",
  "lithium hydroxide": "lithiumhydroxide",
  "live hecate sea worms": "livehecateseaworms",
  "low temperature diamonds": "lowtemperaturediamond",
  "ltt hyper sweet": "ltthypersweet",
  "lucan onionhead": "transgeniconionhead",
  "lyrae weed": "lyraeweed",
  "magnesite": "magnesite",
  "magnetic emitter coil": "magneticemittercoil",
  "marine equipment": "marinesupplies",
  "master chefs": "masterchefs",
  "mechucos high tea": "mechucoshightea",
  "medb starlube": "medbstarlube",
  "medical diagnostic equipment": "medicaldiagnosticequipment",
  "meta-alloys": "metaalloys",
  "methane clathrate": "methaneclathrate",
  "methanol monohydrate crystals": "methanolmonohydratecrystals",
  "micro controllers": "microcontrollers",
  "micro-weave cooling hoses": "coolinghoses",
  "microbial furnaces": "heliostaticfurnaces",
  "military grade fabrics": "militarygradefabrics",
  "military intelligence": "militaryintelligence",
  "military plans": "usscargomilitaryplans",
  "mineral extractors": "mineralextractors",
  "mineral oil": "mineraloil",
  "modular terminals": "modularterminals",
  "moissanite": "moissanite",
  "mokojing beast feast": "mokojingbeastfeast",
  "mollusc brain tissue": "m_tissuesample_nerves",
  "mollusc fluid": "m_tissuesample_fluid",
  "mollusc membrane": "m3_tissuesample_membrane",
  "mollusc mycelium": "m3_tissuesample_mycelium",
  "mollusc soft tissue": "m_tissuesample_soft",
  "mollusc spores": "m3_tissuesample_spores",
  "momus bog spaniel": "momusbogspaniel",
  "monazite": "monazite",
  "motrona experience jelly": "motronaexperiencejelly",
  "mukusubii chitin-os": "mukusubiichitinos",
  "mulachi giant fungus": "mulachigiantfungus",
  "muon imager": "mutomimager",
  "musgravite": "musgravite",
  "mysterious idol": "mysteriousidol",
  "nanobreakers": "nanobreakers",
  "nanomedicines": "nanomedicines",
  "narcotics": "basicnarcotics",
  "natural fabrics": "naturalfabrics",
  "neofabric insulation": "neofabricinsulation",
  "neritus berries": "neritusberries",
  "nerve agents": "nerveagents",
  "ngadandari fire opals": "ngadandarifireopals",
  "nguna modern antiques": "ngunamodernantiques",
  "njangari saddles": "njangarisaddles",
  "non euclidian exotanks": "noneuclidianexotanks",
  "non-lethal weapons": "nonlethalweapons",
  "occupied escape pod": "occupiedcryopod",
  "ochoeng chillies": "ochoengchillies",
  "olivine": "olivine",
  "onionhead": "onionhead",
  "onionhead alpha strain": "onionheada",
  "onionhead beta strain": "onionheadb",
  "onionhead gamma strain": "onionheadc",
  "ophiuch exino artefacts": "ophiuchiexinoartefacts",
  "organ sample": "thargoidorgansample",
  "orrerian vicious brew": "orrerianviciousbrew",
  "osmium": "osmium",
  "painite": "painite",
  "palladium": "palladium",
  "pantaa prayer sticks": "pantaaprayersticks",
  "pavonis ear grubs": "pavoniseargrubs",
  "performance enhancers": "performanceenhancers",
  "periclase dunite": "periclasedunite",
  "personal effects": "personaleffects",
  "personal weapons": "personalweapons",
  "pesticides": "pesticides",
  "platinum": "platinum",
  "platinum alloy": "platinumaloy",
  "pod core tissue": "s_tissuesample_cells",
  "pod dead tissue": "s_tissuesample_surface",
  "pod mesoglea": "s6_tissuesample_mesoglea",
  "pod outer tissue": "s6_tissuesample_cells",
  "pod shell tissue": "s6_tissuesample_coenosarc",
  "pod surface tissue": "s_tissuesample_core",
  "pod tissue": "s9_tissuesample_shell",
  "political prisoners": "politicalprisoner",
  "polymers": "polymers",
  "power converter": "powerconverter",
  "power generators": "powergenerators",
  "power transfer bus": "powertransferconduits",
  "praseodymium": "praseodymium",
  "precious gems": "preciousgems",
  "progenitor cells": "progenitorcells",
  "prohibited research materials": "prohibitedresearchmaterials",
  "protective membrane scrap": "unknownsack",
  "prototype tech": "usscargoprototypetech",
  "pyrophyllite": "pyrophyllite",
  "quartz pyroxenite": "quartzpyroxenite",
  "radiation baffle": "radiationbaffle",
  "rajukru multi-stoves": "rajukrustoves",
  "rapa bao snake skins": "rapabaosnakeskins",
  "rare artwork": "usscargorareartwork",
  "reactive armour": "reactivearmour",
  "rebel transmissions": "usscargorebeltransmissions",
  "reinforced mounting plate": "reinforcedmountingplate",
  "resonating separators": "resonatingseparators",
  "rhodplumsite": "rhodplumsite",
  "robotics": "robotics",
  "rockforth fertiliser": "rockforthfertiliser",
  "ruby": "ruby",
  "rusani old smokey": "rusanioldsmokey",
  "rutile": "rutile",
  "samarium": "samarium",
  "sanuma decorative meat": "sanumameat",
  "sap 8 core container": "sap8corecontainer",
  "sapphire": "sapphire",
  "saxon wine": "saxonwine",
  "scientific research": "scientificresearch",
  "scientific samples": "scientificsamples",
  "scrap": "scrap",
  "semi-refined spire mineral": "unknownrefinedmineral",
  "semiconductors": "semiconductors",
  "serendibite": "serendibite",
  "shan's charis orchid": "shanscharisorchid",
  "silver": "silver",
  "skimmer components": "skimercomponents",
  "slaves": "slaves",
  "small survey data cache": "smallexplorationdatacash",
  "soontill relics": "soontillrelics",
  "sothis crystalline gold": "sothiscrystallinegold",
  "space pioneer relics": "spacepioneerrelics",
  "steel": "steel",
  "structural regulators": "structuralregulators",
  "superconductors": "superconductors",
  "surface stabilisers": "surfacestabilisers",
  "survival equipment": "survivalequipment",
  "synthetic fabrics": "syntheticfabrics",
  "synthetic meat": "syntheticmeat",
  "synthetic reagents": "syntheticreagents",
  "taaffeite": "taaffeite",
  "tactical data": "tacticaldata",
  "tanmark tranquil tea": "tanmarktranquiltea",
  "tantalum": "tantalum",
  "tarach spice": "tarachtorspice",
  "tauri chimes": "taurichimes",
  "tea": "tea",
  "technical blueprints": "usscargotechnicalblueprints",
  "telemetry suite": "telemetrysuite",
  "terra mater blood bores": "terramaterbloodbores",
  "thallium": "thallium",
  "thargoid basilisk tissue sample": "thargoidtissuesampletype2",
  "thargoid biological matter": "unknownbiologicalmatter",
  "thargoid cyclops tissue sample": "thargoidtissuesampletype1",
  "thargoid glaive tissue sample": "thargoidtissuesampletype6",
  "thargoid heart": "thargoidheart",
  "thargoid hydra tissue sample": "thargoidtissuesampletype4",
  "thargoid link": "unknownartifact3",
  "thargoid medusa tissue sample": "thargoidtissuesampletype3",
  "thargoid orthrus tissue sample": "thargoidtissuesampletype5",
  "thargoid probe": "unknownartifact2",
  "thargoid resin": "unknownresin",
  "thargoid scout tissue sample": "thargoidscouttissuesample",
  "thargoid scythe tissue sample": "thargoidtissuesampletype7",
  "thargoid sensor": "unknownartifact",
  "thargoid technology samples": "unknowntechnologysamples",
  "the hutton mug": "thehuttonmug",
  "the waters of shintara": "watersofshintara",
  "thermal cooling units": "thermalcoolingunits",
  "thorium": "thorium",
  "thortveitite": "thortveitite",
  "thrutis cream": "thrutiscream",
  "tiegfries synth silk": "tiegfriessynthsilk",
  "time capsule": "timecapsule",
  "tiolce waste2paste units": "tiolcewaste2pasteunits",
  "titan deep tissue sample": "thargoidtissuesampletype9a",
  "titan drive component": "thargoidtitandrivecomponent",
  "titan maw deep tissue sample": "thargoidtissuesampletype10a",
  "titan maw partial tissue sample": "thargoidtissuesampletype10c",
  "titan maw tissue sample": "thargoidtissuesampletype10b",
  "titan partial tissue sample": "thargoidtissuesampletype9c",
  "titan tissue sample": "thargoidtissuesampletype9b",
  "titanium": "titanium",
  "tobacco": "tobacco",
  "toxandji virocide": "toxandjivirocide",
  "toxic waste": "toxicwaste",
  "trade data": "usscargotradedata",
  "trinkets of hidden fortune": "trinketsoffortune",
  "tritium": "tritium",
  "ultra-compact processor prototypes": "advert1",
  "unclassified relic": "ancientrelictg",
  "unoccupied escape pod": "unocuppiedescapepod",
  "unstable data core": "unstabledatacore",
  "uraninite": "uraninite",
  "uranium": "uranium",
  "uszaian tree grub": "uszaiantreegrub",
  "utgaroar millennial eggs": "utgaroarmillenialeggs",
  "uzumoku low-g wings": "uzumokulowgwings",
  "v herculis body rub": "vherculisbodyrub",
  "vanayequi ceratomorpha fur": "vanayequirhinofur",
  "vega slimweed": "vegaslimweed",
  "vidavantian lace": "vidavantianlace",
  "void extract coffee": "lftvoidextractcoffee",
  "void opal": "opal",
  "volkhab bee drones": "volkhabbeedrones",
  "water": "water",
  "water purifiers": "waterpurifiers",
  "wheemete wheat cakes": "wheemetewheatcakes",
  "wine": "wine",
  "witchhaul kobe beef": "witchhaulkobebeef",
  "wolf fesh": "wolf1301fesh",
  "wreckage components": "wreckagecomponents",
  "wulpa hyperbore systems": "wulpahyperboresystems",
  "wuthielo ku froth": "wuthielokufroth",
  "xenobiological prison pod": "thargoidpod",
  "xihe biomorphic companions": "xihecompanions",
  "yaso kondi leaf": "yasokondileaf",
  "zeessze ant grub glue": "zeesszeantglue",
};

export function symbolFor(name) {
  const key = String(name || "").trim().toLowerCase();
  return SYMBOLS[key] || key.replace(/[^a-z0-9]/g, "");
}
